### ISSUE TITLE
ScrollablePlotArea: X Position while scrolling

### ISSUE THREAD

**Issue by DarrenAndes** [highcharts/highcharts-ios#108]
On a column chart using scrollablePlotArea, Is there a way (ie. event callback) to get the X position while you swipe left / right?

**Comment by sebastianbochan** [comment]
Hi @DarrenAndes,
Please let me know if ,by x-position, you mean x value after swipe? In example you touch the screen on x = 10 (lets sey column) , swipe into right and then you would like to have know, where you finger is, correct?

**Comment by DarrenAndes** [comment]
@sebastianbochan Sorry that my example confused the question.

I simply need a way (ie. event) that when you scroll the chart when using the ScrollablePlotArea you can get the X position (ie. contentOffset) allowing you to do other functionality in other parts of the screen outside the chart.

**Comment by sebastianbochan** [comment]
Hi @DarrenAndes,
Thank you for the feedback and now I understand what you need. 

Unfortunately at this moment this kind of callback is not available, because functionality is realized by CSS `overflow-x` option. 

In native JS, you can catch the `scroll` event and try to calculate position, but in iOS its not possible (different way of rendering object).

**Comment by ihnatmoisieiev** [comment]
@DarrenAndes can I close it?
