### ISSUE TITLE
BUG (?): Blue box around Pie / Donut chart segment

### ISSUE THREAD

**Issue by skuske** [highcharts/highcharts-ios#443]
Sometimes a blue selection box appears around a pie/donut diagram when you select it with your finger. I can't say exactly how to reproduce this 100%, but some touches with the finger provoke the appearance of this blue box. This is extremely annoying as users do not understand the purpose of this box. How can I prevent this box from appearing? The problem exists with every Pie / Donut Chart, including the iOS demos. 

I am **not** using the accessibility module / plugin.

I urgently ask for help!

![IMG_3508](https://github.com/highcharts/highcharts-ios/assets/12996815/a17a802b-7e73-421f-87e9-7adce7ae78bc)

**Comment by skuske** [comment]
The following fixes the problem. However, strange that 'accessibility' has to be explicitly deactivated, **especially since the 'Accessibility' module / plugin is not loaded or used** in the chart. Seems to be a bug that it is somewhat active.

```
    HIAccessibility *accessibility = [HIAccessibility new];
    accessibility.enabled=@0;
```

**Comment by MikolajMichalczak** [comment]
Hi @skuske!

Thank you for bringing this issue to our attention. We understand your concerns regarding this behavior. However, accessibility is considered a desirable feature, which is why it is enabled by default. Changing this default behavior would be a breaking change for users who currently rely on it. Therefore, we have decided not to alter this setting.

If you do not need the accessibility module, you can disable it using the code snippet you provided earlier.
We appreciate your understanding and feedback.
